//! Generate an ML-DSA-44 key pair and signature for `esp-probe` to verify.
//!
//! # Why generate rather than transcribe
//!
//! LMS is measured against RFC 8554's published vectors, which is strictly better:
//! a pass there means the implementation agrees with the standard. There is no
//! equivalent here, because the point of the ML-DSA probe is not to check
//! RustCrypto's correctness — it is to weigh their code and time it on real
//! silicon.
//!
//! What matters for that is only that the signature is genuine, so verification
//! does the full amount of work rather than rejecting early. A locally generated
//! pair gives exactly that.
//!
//! Committing the generator rather than only the hex is the point: a constant
//! nobody can reproduce is a magic number.
//!
//! `cargo run --release` from this directory, and paste the output into
//! `esp-probe/src/mldsa_vector.rs`.

use ml_dsa::signature::{Keypair, Signer, Verifier};
use ml_dsa::{Generate, MlDsa44, SigningKey};

fn emit(name: &str, bytes: &[u8]) {
    println!("/// {} bytes.", bytes.len());
    println!("pub const {name}: [u8; {}] = [", bytes.len());
    for chunk in bytes.chunks(16) {
        print!("   ");
        for b in chunk {
            print!(" 0x{b:02x},");
        }
        println!();
    }
    println!("];\n");
}

fn main() {
    // `generate()` pulls from the OS RNG itself; no rng argument to pass.
    let sk = SigningKey::<MlDsa44>::generate();
    let vk = sk.verifying_key();

    let msg = b"firmware image v1.2.3";
    let sig = sk.sign(msg);

    // Never emit a vector that does not verify. A signature the probe rejects
    // would measure the rejection path, which is not the thing being measured.
    assert!(
        vk.verify(msg, &sig).is_ok(),
        "generated signature does not verify"
    );

    println!("//! ML-DSA-44 vector, generated by tools/gen-mldsa-vector.");
    println!("//!");
    println!("//! Not a standard test vector — see that tool for why one is not used here.\n");
    emit("PK", &vk.encode());
    emit("SIG", &sig.encode());
    emit("MSG", msg);
}
