//! Generate an FN-DSA-512 key pair and signature for `esp-probe` to verify.
//!
//! # Why generate rather than transcribe
//!
//! Same reason as `gen-mldsa-vector`. LMS is measured against RFC 8554's
//! published vectors, which is strictly better: a pass there means the
//! implementation agrees with the standard. There is no equivalent here,
//! because the point of this probe is not to check Pornin's correctness — it is
//! to weigh the code and measure its stack on real silicon.
//!
//! What matters for that is only that the signature is genuine, so verification
//! does the full amount of work instead of rejecting early. A locally generated
//! pair gives exactly that.
//!
//! Committing the generator rather than only the hex is the point: a constant
//! nobody can reproduce is a magic number.
//!
//! The message is the same 162-byte string the LMS probe verifies, so the three
//! schemes on the chip are timed over the same input rather than over whatever
//! each vector happened to carry.
//!
//! `cargo run --release` from this directory, and paste the output into
//! `esp-probe/src/fndsa_vector.rs`.

use rand_core::OsRng;
use fn_dsa::{
    sign_key_size, signature_size, vrfy_key_size, FN_DSA_LOGN_512, KeyPairGenerator,
    KeyPairGeneratorStandard, SigningKey, SigningKeyStandard, VerifyingKey, VerifyingKeyStandard,
    DOMAIN_NONE, HASH_ID_RAW,
};

/// The RFC 8554 Appendix F message, so every scheme on the chip signs the same
/// bytes.
const MSG: &[u8] = b"The powers not delegated to the United States by the Constitution, nor prohibited by it to the States, are reserved to the States respectively, or to the people.\n";

fn emit(name: &str, bytes: &[u8]) {
    println!("/// {} bytes.", bytes.len());
    println!("pub const {name}: [u8; {}] = [", bytes.len());
    for chunk in bytes.chunks(16) {
        print!("   ");
        for b in chunk {
            print!(" 0x{b:02x},");
        }
        println!();
    }
    println!("];");
    println!();
}

fn main() {
    let mut kg = KeyPairGeneratorStandard::default();
    let mut sign_key = [0u8; sign_key_size(FN_DSA_LOGN_512)];
    let mut vrfy_key = [0u8; vrfy_key_size(FN_DSA_LOGN_512)];
    kg.keygen(FN_DSA_LOGN_512, &mut OsRng, &mut sign_key, &mut vrfy_key);

    let mut sk = SigningKeyStandard::decode(&sign_key).expect("signing key decodes");
    let mut sig = vec![0u8; signature_size(sk.get_logn())];
    sk.sign(&mut OsRng, &DOMAIN_NONE, &HASH_ID_RAW, MSG, &mut sig);

    // Never emit a vector that does not verify. The probe measures the cost of a
    // successful verification; a signature that fails early would measure nothing.
    let vk = VerifyingKeyStandard::decode(&vrfy_key).expect("verifying key decodes");
    assert!(
        vk.verify(&sig, &DOMAIN_NONE, &HASH_ID_RAW, MSG),
        "generated signature does not verify"
    );

    println!("//! FN-DSA-512 vector, generated by tools/gen-fndsa-vector.");
    println!("//!");
    println!("//! Not a standard test vector — see that tool for why one is not used here.");
    println!();
    emit("PK", &vrfy_key);
    emit("SIG", &sig);
    emit("MSG", MSG);
}
